-- Script de inicialização simplificado para Oracle XE
-- Sistema de Cálculo de Perdas - Cana-de-Açúcar

-- Criar tabela principal de produção de cana
CREATE TABLE producao_cana (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    localizacao VARCHAR2(100) NOT NULL,
    area_plantada_ha NUMBER(10,2) NOT NULL CHECK (area_plantada_ha > 0),
    qtd_colhida_toneladas NUMBER(12,2) NOT NULL CHECK (qtd_colhida_toneladas >= 0),
    tipo_colheita VARCHAR2(20) NOT NULL CHECK (tipo_colheita IN ('manual', 'mecanizada')),
    data_colheita DATE NOT NULL,
    variedade_cana VARCHAR2(50),
    idade_cana_meses NUMBER(3) CHECK (idade_cana_meses > 0),
    umidade_solo NUMBER(5,2) CHECK (umidade_solo BETWEEN 0 AND 100),
    temperatura_media NUMBER(4,1),
    precipitacao_mm NUMBER(6,2) CHECK (precipitacao_mm >= 0),
    produtividade_toneladas_ha NUMBER(6,2) GENERATED ALWAYS AS (qtd_colhida_toneladas / area_plantada_ha),
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Criar tabela para armazenar cálculos de perdas
CREATE TABLE perdas_colheita (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producao_id NUMBER NOT NULL,
    perda_estimada_toneladas NUMBER(10,2) NOT NULL CHECK (perda_estimada_toneladas >= 0),
    percentual_perda NUMBER(5,2) NOT NULL CHECK (percentual_perda BETWEEN 0 AND 100),
    fatores_perda CLOB, -- JSON com fatores que contribuíram para a perda
    metodo_calculo VARCHAR2(50) NOT NULL,
    observacoes VARCHAR2(500),
    calculado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (producao_id) REFERENCES producao_cana(id) ON DELETE CASCADE
);

-- Criar tabela para parâmetros de cálculo de perdas
CREATE TABLE parametros_perdas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_colheita VARCHAR2(20) NOT NULL CHECK (tipo_colheita IN ('manual', 'mecanizada')),
    fator_base_perda NUMBER(4,3) NOT NULL CHECK (fator_base_perda BETWEEN 0 AND 1),
    fator_umidade NUMBER(4,3) DEFAULT 0,
    fator_idade NUMBER(4,3) DEFAULT 0,
    fator_clima NUMBER(4,3) DEFAULT 0,
    descricao VARCHAR2(200),
    ativo CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S', 'N')),
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tipo_colheita, ativo)
);

-- Inserir parâmetros padrão para cálculo de perdas
INSERT INTO parametros_perdas (tipo_colheita, fator_base_perda, fator_umidade, fator_idade, fator_clima, descricao) VALUES
('manual', 0.05, 0.02, 0.01, 0.015, 'Parâmetros para colheita manual - perda base 5%');

INSERT INTO parametros_perdas (tipo_colheita, fator_base_perda, fator_umidade, fator_idade, fator_clima, descricao) VALUES
('mecanizada', 0.08, 0.025, 0.015, 0.02, 'Parâmetros para colheita mecanizada - perda base 8%');

-- Criar índices para melhor performance
CREATE INDEX idx_producao_data ON producao_cana(data_colheita);
CREATE INDEX idx_producao_tipo ON producao_cana(tipo_colheita);
CREATE INDEX idx_producao_local ON producao_cana(localizacao);
CREATE INDEX idx_perdas_producao ON perdas_colheita(producao_id);

-- Criar view para relatórios consolidados
CREATE OR REPLACE VIEW vw_relatorio_perdas AS
SELECT 
    p.id,
    p.localizacao,
    p.area_plantada_ha,
    p.qtd_colhida_toneladas,
    p.tipo_colheita,
    p.data_colheita,
    p.produtividade_toneladas_ha,
    l.perda_estimada_toneladas,
    l.percentual_perda,
    l.metodo_calculo,
    l.calculado_em,
    (p.qtd_colhida_toneladas + l.perda_estimada_toneladas) AS producao_potencial_toneladas
FROM producao_cana p
LEFT JOIN perdas_colheita l ON p.id = l.producao_id
ORDER BY p.data_colheita DESC;

-- Inserir dados de exemplo para teste
INSERT INTO producao_cana (localizacao, area_plantada_ha, qtd_colhida_toneladas, tipo_colheita, data_colheita, variedade_cana, idade_cana_meses, umidade_solo, temperatura_media, precipitacao_mm) VALUES
('Fazenda São José - Talhão 1', 50.5, 4040.0, 'mecanizada', DATE '2024-07-15', 'RB92579', 12, 65.5, 28.5, 1250.0);

INSERT INTO producao_cana (localizacao, area_plantada_ha, qtd_colhida_toneladas, tipo_colheita, data_colheita, variedade_cana, idade_cana_meses, umidade_solo, temperatura_media, precipitacao_mm) VALUES
('Fazenda Boa Vista - Setor A', 25.0, 1750.0, 'manual', DATE '2024-08-10', 'SP813250', 14, 58.0, 29.0, 980.5);

INSERT INTO producao_cana (localizacao, area_plantada_ha, qtd_colhida_toneladas, tipo_colheita, data_colheita, variedade_cana, idade_cana_meses, umidade_solo, temperatura_media, precipitacao_mm) VALUES
('Usina Central - Área 3', 120.0, 10800.0, 'mecanizada', DATE '2024-09-05', 'CTC4', 11, 72.0, 27.5, 1450.2);

-- Commit das alterações
COMMIT;